Add database First Try
V-Levchenkov/java-filmorate-main pull request #4
Opened 2022-07-14 17:24 UTC by V-Levchenkov

2022-07-16 11:58 UTC, kukolev requested changes

2022-07-16 11:58 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmId <= 0) {
Валидация параметров это часть логики приложения. Валидацию нужно делать в рамках сервиса. 

Аналогично нужно поправить ниже.

2022-07-16 11:58 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT * FROM FILMS AS F " + "LEFT JOIN FILM_GENRES FG ON F.FILM_ID = FG.FILM_ID " + "LEFT JOIN MPA_RATING MR ON MR.RATING_ID = F.MPA_RATING_ID " + "LEFT JOIN GENRES G ON G.GENR
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-16 11:58 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        String sql = "SELECT * FROM GENRES WHERE GENRE_ID = ?";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-16 11:58 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        String sql = "SELECT * FROM MPA_RATING WHERE RATING_ID = ?";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-16 11:58 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "SELECT * FROM USERS WHERE USER_ID = ?";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-16 16:50 UTC, V-Levchenkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmId <= 0) {
Done

2022-07-16 16:51 UTC, V-Levchenkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT * FROM FILMS AS F " + "LEFT JOIN FILM_GENRES FG ON F.FILM_ID = FG.FILM_ID " + "LEFT JOIN MPA_RATING MR ON MR.RATING_ID = F.MPA_RATING_ID " + "LEFT JOIN GENRES G ON G.GENR
DONE

2022-07-16 17:54 UTC, V-Levchenkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        String sql = "SELECT * FROM GENRES WHERE GENRE_ID = ?";
DONE

2022-07-16 17:54 UTC, V-Levchenkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        String sql = "SELECT * FROM MPA_RATING WHERE RATING_ID = ?";
DONE

2022-07-16 17:54 UTC, V-Levchenkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "SELECT * FROM USERS WHERE USER_ID = ?";
DONE

2022-07-17 13:02 UTC, kukolev requested changes

2022-07-18 03:31 UTC, V-Levchenkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final FilmStorage filmStorage;
Прошу обратить внимание :  в коде контроллеры работают только с сервисами, которые работают с интерфейсами хранилищ, т.е. всё ок

2022-07-18 07:23 UTC, V-Levchenkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final FilmStorage filmStorage;
Комментарий добавлен к Service

2022-07-18 07:47 UTC, kukolev approved these changes

2022-07-18 08:12 UTC, merged